function cbs(u){var ua=u.toLowerCase(),is=function(t){return ua.indexOf(t)>-1},g='gecko',w='webkit',s='safari',h=document.getElementsByTagName('html')[0],b=[(!(/opera|webtv/i.test(ua))&&/msie\s(\d)/.test(ua))?('ie ie'+RegExp.$1):is('firefox/2')?g+' ff2':is('firefox/3')?g+' ff3':is('gecko/')?g:/opera(\s|\/)(\d+)/.test(ua)?'opera opera'+RegExp.$2:is('konqueror')?'konqueror':is('chrome')?w+' chrome':is('applewebkit/')?w+' '+s+(/version\/(\d+)/.test(ua)?' '+s+RegExp.$1:''):is('mozilla/')?g:'',is('j2me')?'mobile':is('iphone')?'iphone':is('ipod')?'ipod':is('mac')?'mac':is('darwin')?'mac':is('webtv')?'webtv':is('win')?'win':is('freebsd')?'freebsd':(is('x11')||is('linux'))?'linux':'','js']; c=b.join(' '); h.className+=' '+c; return c}; cbs(navigator.userAgent); document.write("<script src='inc/lb/lb.js'></script><script src='inc/mb/mo.js'></script><script src='inc/mb/mb.js'></script><script src='inc/ac/ac.js'></script>"); var pn=location.pathname.slice(1,-4); $.noConflict(); var j=jQuery.noConflict(); j(document).ready(function($){if(pn!="photos"){$("[href^='"+pn.replace("&","and")+"']").addClass("ac")}else{$(".lt").css("background","none"); $("[href^='photos.php"+location.search.replace("%20"," ").replace("%20"," ").replace("%20"," ").replace("%20"," ")+"']").addClass("ac")}

$("a[name]").css("visibility","hidden"); $("#p img").mouseover(function(){ $(this).attr("src","inc/_img/f2.png").mouseout(function(){$(this).attr("src","inc/_img/f1.png")})}); $(".mb").attr("rel","width:480,height:360");
  if(pn=="company-profile2"){$("#gr,.gr").show(); $("#ln li").addClass("c"); $("#ln li:eq(0)").addClass("ac"); $("#gr div:gt(0)").hide(); $(".c").click(function(){
var i=$(this).index()-1; $("#ln li").removeClass("ac"); $("#ln li:eq("+i+")").addClass("ac"); $("#gr div").hide(); $("#gr div:eq("+i+")").show()})}
  $("input:submit").addClass("g"); $("input,textarea").each(function(){var n=!$(this).attr("name")?"":$(this).attr("name"); var e=n.slice(0,1).toUpperCase()+n.slice(1).replace("_n"," N")+":"; $(this).val(e); $(this).focus(function(){$(this).val("")}).blur(function(){if(!$(this).val()) $(this).val(e)})});
  $("option").each(function(){$(this).val($(this).text())}); $(".dt").hide(); $("#course").change(function(){var i=$("option:selected",this).index(); i--; $(".dt,#b1").hide(); $(".dt:eq("+i+")").show(); $(".or").height(154)}); $(".dt").change(function(){$("#b2").hide()});
  $(".g").click(function(){if($("#course").val()=="Select a course..."){$("#b1").show()}else if($(".dt:visible").val()=="Select a date..."){$("#b2").show()}
  else if($("[name='email']").val()=="Email:"&&$("[name='phone']").val()=="Phone:"){$("#b3").show()}else{$("form").attr("action","inc/nv.php").submit()}});

  //$("#p a:eq(0)").remove(); $("#p").html($("#p").html()+"<a href='./pics/4-explosively-severed-multi-string-wells.jpg' rel='lb' style='background:url(./pics/4-explosively-severed-multi-string-wells.jpg); background-size:150px auto;'><img src='inc/_img/f1.png'></a>");
  $("#p").html('<a href="./pics/4-pile-post-shot-1.jpg" rel="lb" style="background:url(./pics/4-pile-post-shot-1.jpg); background-size:150px auto;"><img src="inc/_img/f1.png"></a><a href="./pics/4-pile-post-shot-2.jpg" rel="lb" style="background:url(./pics/4-pile-post-shot-2.jpg); background-size:150px auto;"><img src="inc/_img/f1.png"></a><a href="./pics/4-pile-post-shot-3.jpg" rel="lb" style="background:url(./pics/4-pile-post-shot-3.jpg); background-size:150px auto;"><img src="inc/_img/f1.png"></a><a href="./pics/4-pile-removal.jpg" rel="lb" style="background:url(./pics/4-pile-removal.jpg); background-size:150px auto;"><img src="inc/_img/f1.png"></a><a href="./pics/4-pile-structure.jpg" rel="lb" style="background:url(./pics/4-pile-structure.jpg); background-size:150px auto;"><img src="inc/_img/f1.png"></a>');
});